version: "3.8"

services:
  front:
    image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}-${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}"
    build: ""
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${CI_PROJECT_NAME}.rule=Host(`${SUB_DOMAIN}.${DEV_URL}`)"
        - "traefik.http.routers.${CI_PROJECT_NAME}.entrypoints=web"
        - "traefik.http.routers.${CI_PROJECT_NAME}.middlewares=webtowebsecure"
        - "traefik.http.routers.${CI_PROJECT_NAME}-secured.rule=Host(`${SUB_DOMAIN}.${DEV_URL}`)"
        - "traefik.http.routers.${CI_PROJECT_NAME}-secured.entrypoints=websecure"
        - "traefik.http.routers.${CI_PROJECT_NAME}-secured.tls=true"
        - "traefik.http.routers.${CI_PROJECT_NAME}-secured.tls.certresolver=le"
        - "traefik.http.services.${CI_PROJECT_NAME}.loadbalancer.server.port=80"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    networks:
      - default
      - traefik-public

networks:
  traefik-public:
    external: true
  default:
    external: true
    name: sky-net
